spring.application.name=ArquiteturaHexagonal
server.port=8081
#postgress docker
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres-hexagonal
spring.datasource.username=postgress
spring.datasource.password=postgress
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.hibernate.ddl-auto=auto


logging.level.com.produtos.ArquiteturaHexagonal.externals.api=DEBUG
logging.level.org.springframework.security=DEBUG

api.security.token.secret=e9a3b6c7d8e9f0a1b2c3d4e5f6a7b8c97d8e4e5f7d8e9f0a1b2c3d4e5